### PR TITLE
remove SyberiaStages dependency + fix Travis

### PR DESCRIPTION
**Pull request by abelcastilloavant**

### CODE REVIEW

**Comment by abelcastilloavant** [comment]
All tests pass when using `test_engine` locally. @robertzk ideas on what might have gone wrong?

**Comment by abelcastilloavant** [comment]
Error message from Travis suggest problems with the `methods` package:

> Running tests...
> simpleError in if (rep$context_open) {    rep$end_context()} else {    rep$context_open <- TRUE}: argument is of length zero
> Warning messages:
> 1: 'package:methods' may not be available when loading 
> 2: 'package:methods' may not be available when loading 
> 3: 'package:methods' may not be available when loading 
> 4: 'package:methods' may not be available when loading 
> 5: 'package:methods' may not be available when loading

**Comment by peterhurford** [comment]
@abelcastilloavant - Travis is still pretty buggy for this, but we're working on it.

**Comment by abelcastilloavant** [comment]
Does that mean this is ready to merge? @peterhurford

**Comment by peterhurford** [comment]
Wait for @robertzk to review and approve.

**Comment by robertzk** [comment]
Trying to get the tests working.

**Comment by abelcastilloavant** [comment]
Travis is reporting a success, even though there was an error during the run in: https://travis-ci.org/syberia/modeling.sy/builds/124830292#L493

> lib/adapters/s3: Error in library(s3mpi) : there is no package called ‘s3mpi’

The attempt to load the library comes from here: https://travis-ci.org/syberia/modeling.sy/builds/124830292#L547

> In /home/travis/build/syberia/modeling.sy/test/lib/adapters/s3.R:3: library(s3mpi)

**Comment by peterhurford** [comment]
Oh yeah @robertzk and I never did fix that thing we did to Travis to make it always report success 😨

**Comment by peterhurford** [comment]
Hold off on merging; I'll fix in another PR.

**Comment by peterhurford** [comment]
@abelcastilloavant Just put this change https://github.com/syberia/modeling.sy/pull/13 in your branch and I'll close my PR. Looks like I'm also having the same s3mpi issue.

**Comment by abelcastilloavant** [comment]
@peterhurford done.

**Comment by peterhurford** [comment]
Nice.  Now add `s3mpi` to the lockfile: https://github.com/syberia/modeling.sy/blob/master/lockfile.yml

**Comment by peterhurford** [comment]
and revert https://github.com/syberia/modeling.sy/pull/8/commits/c4e797707831898acc844a53e73f3f7f8ff595e6

**Comment by peterhurford** [comment]
...Looks like `AWS.tools` went off CRAN again. What a weird package.

**Comment by abelcastilloavant** [comment]
I was about to say. Does this mean adding it as a remote to s3mpi?

**Comment by peterhurford** [comment]
@abelcastilloavant Yep. https://github.com/robertzk/s3mpi/pull/45

**Comment by peterhurford** [comment]
@abelcastilloavant Ready

**Comment by abelcastilloavant** [comment]
Woohoo, tests pass! Now to remove the SyberiaStages package.

**Comment by peterhurford** [comment]
Let's wait for @robertzk to LGTM and then merge.  Looks good to me, though.

**Comment by peterhurford** [comment]
@abelcastilloavant Try taking out `syberiaStructure` too and see if tests still pass.

**Comment by peterhurford** [comment]
@abelcastilloavant Awesome that tests pass!

**Comment by robertzk** [comment]
Thanks!

**Pull request merged**
